# Module 12: Infrastructure Files - Vagrantfile
# Sets up three virtual machines for local development:
# - scriptbox (Ubuntu 22.04 LTS)
# - web01 (CentOS Stream 9)
# - web02 (CentOS Stream 9)

Vagrant.configure("2") do |config|

  # 1. Scriptbox (automation machine)
  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "ubuntu/jammy64"
    scriptbox.vm.hostname = "scriptbox"
    scriptbox.vm.network "private_network", ip: "192.168.10.2"
  end

  # 2. Web Server 01
  config.vm.define "web01" do |web01|
    web01.vm.box = "eurolinux-vagrant/centos-stream-9"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.10.3"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
  
  # 3. Web Server 02
  config.vm.define "web02" do |web02|
    web02.vm.box = "eurolinux-vagrant/centos-stream-9"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.10.4"
  end
  
end
